import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { headers } from "next/headers";
import { AppSidebar } from "@/components/dashboard/app-sidebar";
import { Toaster } from "@/components/ui/sonner";
import { AppProviders } from "./providers";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
                                             children,
                                         }: {
    children: React.ReactNode;
}) {
    const headerList = await headers();
    const pathname = headerList.get("x-pathname") || "";
    console.log(pathname);
    const isPublicPage = ["/login", "/register"].includes(pathname);

    return (
        <html lang="en" suppressHydrationWarning>
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AppProviders>
            {isPublicPage ? (
                <>
                    {children}
                    <Toaster richColors position="top-right" />
                </>
            ) : (
                <div className="w-full flex min-h-screen">
                    <AppSidebar />
                    <main className="flex-1 min-h-screen p-6">
                        <div className="ml-auto mr-auto w-full max-w-4xl px-4">
                            {children}
                        </div>
                        <Toaster richColors position="top-right" />
                    </main>
                </div>
            )}
        </AppProviders>
        </body>
        </html>
    );
}
